// Auto-generated precompiled header
// Target: echosounders:echosounders_nanopy
#pragma once

#if !defined(__WIN32__) && !defined(_WIN32) && !defined(__WIN64__) && !defined(_WIN64)
#include <nanobind/nanobind.h>
#include <nanobind/stl/complex.h>
#include <nanobind/stl/map.h>
#include <nanobind/stl/optional.h>
#include <nanobind/stl/shared_ptr.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/string_view.h>
#include <nanobind/stl/unordered_map.h>
#include <nanobind/stl/variant.h>
#include <nanobind/stl/vector.h>
#endif
#include <Eigen/Core>
#include <Eigen/Dense>
#include <algorithm>
#include <array>
#include <bitset>
#include <boost/algorithm/string.hpp>
#include <boost/flyweight.hpp>
#include <boost/flyweight/key_value.hpp>
#include <boost/iostreams/device/mapped_file.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/sort/sort.hpp>
#include <boost/unordered_map.hpp>
#include <chrono>
#include <cmath>
#include <complex>
#include <cstdint>
#include <deque>
#include <filesystem>
#include <fmt/core.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <frozen/map.h>
#include <frozen/string.h>
#include <frozen/unordered_map.h>
#include <fstream>
#include <iosfwd>
#include <iostream>
#include <limits>
#include <magic_enum/magic_enum.hpp>
#include <map>
#include <memory>
#include <numbers>
#include <optional>
#include <pugixml.hpp>
#include <set>
#include <sstream>
#include <stdexcept>
#include <stdint.h>
#include <string>
#include <string_view>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>
#include <xtensor/containers/xadapt.hpp>
#include <xtensor/containers/xtensor.hpp>
#include <xtensor/core/xmath.hpp>
#include <xtensor/core/xshape.hpp>
#include <xtensor/io/xio.hpp>
#include <xtensor/misc/xmanipulation.hpp>
#include <xtensor/views/xindex_view.hpp>
#include <xtensor/views/xview.hpp>
#include <xxhash.hpp>
