// SPDX-FileCopyrightText: 2022 - 2025 Peter Urban, Ghent University
//
// SPDX-License-Identifier: MPL-2.0

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>

#include <themachinethatgoesping/tools_nanobind/classhelper.hpp>
#include <themachinethatgoesping/tools_nanobind/datetime.hpp>

#include "../../themachinethatgoesping/echosounders/s7k/datagrams/referencepoint.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/position.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/rollpitchheave.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/heading.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/navigation.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/sonarsettings.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/matchfilter.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/soundvelocity.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/absorptionloss.hpp"
#include "../../themachinethatgoesping/echosounders/s7k/datagrams/spreadingloss.hpp"

#include "module.hpp"

// generated by tools/gen_s7k_records.py for the fixed-RTH s7k records

namespace themachinethatgoesping {
namespace echosounders {
namespace pymodule {
namespace py_s7k {
namespace nb = nanobind;
using namespace themachinethatgoesping::echosounders::s7k;
using namespace themachinethatgoesping::echosounders::s7k::datagrams;

#define DOC_C(CLASS, ARG) DOC(themachinethatgoesping, echosounders, s7k, datagrams, CLASS, ARG)

void init_c_referencepoint(nb::module_& m)
{
    nb::class_<ReferencePoint, S7KDatagram>(m, "ReferencePoint", DOC(themachinethatgoesping, echosounders, s7k, datagrams, ReferencePoint))
        .def(nb::init<>(), DOC_C(ReferencePoint, ReferencePoint))
        .def("get_offset_x", &ReferencePoint::get_offset_x, DOC_C(ReferencePoint, get_offset_x))
        .def("set_offset_x", &ReferencePoint::set_offset_x, DOC_C(ReferencePoint, set_offset_x), nb::arg("val"))
        .def("get_offset_y", &ReferencePoint::get_offset_y, DOC_C(ReferencePoint, get_offset_y))
        .def("set_offset_y", &ReferencePoint::set_offset_y, DOC_C(ReferencePoint, set_offset_y), nb::arg("val"))
        .def("get_offset_z", &ReferencePoint::get_offset_z, DOC_C(ReferencePoint, get_offset_z))
        .def("set_offset_z", &ReferencePoint::set_offset_z, DOC_C(ReferencePoint, set_offset_z), nb::arg("val"))
        .def("get_water_z", &ReferencePoint::get_water_z, DOC_C(ReferencePoint, get_water_z))
        .def("set_water_z", &ReferencePoint::set_water_z, DOC_C(ReferencePoint, set_water_z), nb::arg("val"))
        .def("__eq__", &ReferencePoint::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(ReferencePoint)
        __PYCLASS_DEFAULT_BINARY__(ReferencePoint)
        __PYCLASS_DEFAULT_PRINTING__(ReferencePoint);
}

void init_c_position(nb::module_& m)
{
    nb::class_<Position, S7KDatagram>(m, "Position", DOC(themachinethatgoesping, echosounders, s7k, datagrams, Position))
        .def(nb::init<>(), DOC_C(Position, Position))
        .def("get_datum", &Position::get_datum, DOC_C(Position, get_datum))
        .def("set_datum", &Position::set_datum, DOC_C(Position, set_datum), nb::arg("val"))
        .def("get_latency", &Position::get_latency, DOC_C(Position, get_latency))
        .def("set_latency", &Position::set_latency, DOC_C(Position, set_latency), nb::arg("val"))
        .def("get_latitude_northing", &Position::get_latitude_northing, DOC_C(Position, get_latitude_northing))
        .def("set_latitude_northing", &Position::set_latitude_northing, DOC_C(Position, set_latitude_northing), nb::arg("val"))
        .def("get_longitude_easting", &Position::get_longitude_easting, DOC_C(Position, get_longitude_easting))
        .def("set_longitude_easting", &Position::set_longitude_easting, DOC_C(Position, set_longitude_easting), nb::arg("val"))
        .def("get_height", &Position::get_height, DOC_C(Position, get_height))
        .def("set_height", &Position::set_height, DOC_C(Position, set_height), nb::arg("val"))
        .def("get_position_type", &Position::get_position_type, DOC_C(Position, get_position_type))
        .def("set_position_type", &Position::set_position_type, DOC_C(Position, set_position_type), nb::arg("val"))
        .def("get_utm_zone", &Position::get_utm_zone, DOC_C(Position, get_utm_zone))
        .def("set_utm_zone", &Position::set_utm_zone, DOC_C(Position, set_utm_zone), nb::arg("val"))
        .def("get_quality", &Position::get_quality, DOC_C(Position, get_quality))
        .def("set_quality", &Position::set_quality, DOC_C(Position, set_quality), nb::arg("val"))
        .def("get_position_method", &Position::get_position_method, DOC_C(Position, get_position_method))
        .def("set_position_method", &Position::set_position_method, DOC_C(Position, set_position_method), nb::arg("val"))
        .def("__eq__", &Position::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(Position)
        __PYCLASS_DEFAULT_BINARY__(Position)
        __PYCLASS_DEFAULT_PRINTING__(Position);
}

void init_c_rollpitchheave(nb::module_& m)
{
    nb::class_<RollPitchHeave, S7KDatagram>(m, "RollPitchHeave", DOC(themachinethatgoesping, echosounders, s7k, datagrams, RollPitchHeave))
        .def(nb::init<>(), DOC_C(RollPitchHeave, RollPitchHeave))
        .def("get_roll", &RollPitchHeave::get_roll, DOC_C(RollPitchHeave, get_roll))
        .def("set_roll", &RollPitchHeave::set_roll, DOC_C(RollPitchHeave, set_roll), nb::arg("val"))
        .def("get_pitch", &RollPitchHeave::get_pitch, DOC_C(RollPitchHeave, get_pitch))
        .def("set_pitch", &RollPitchHeave::set_pitch, DOC_C(RollPitchHeave, set_pitch), nb::arg("val"))
        .def("get_heave", &RollPitchHeave::get_heave, DOC_C(RollPitchHeave, get_heave))
        .def("set_heave", &RollPitchHeave::set_heave, DOC_C(RollPitchHeave, set_heave), nb::arg("val"))
        .def("__eq__", &RollPitchHeave::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(RollPitchHeave)
        __PYCLASS_DEFAULT_BINARY__(RollPitchHeave)
        __PYCLASS_DEFAULT_PRINTING__(RollPitchHeave);
}

void init_c_heading(nb::module_& m)
{
    nb::class_<Heading, S7KDatagram>(m, "Heading", DOC(themachinethatgoesping, echosounders, s7k, datagrams, Heading))
        .def(nb::init<>(), DOC_C(Heading, Heading))
        .def("get_heading", &Heading::get_heading, DOC_C(Heading, get_heading))
        .def("set_heading", &Heading::set_heading, DOC_C(Heading, set_heading), nb::arg("val"))
        .def("__eq__", &Heading::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(Heading)
        __PYCLASS_DEFAULT_BINARY__(Heading)
        __PYCLASS_DEFAULT_PRINTING__(Heading);
}

void init_c_navigation(nb::module_& m)
{
    nb::class_<Navigation, S7KDatagram>(m, "Navigation", DOC(themachinethatgoesping, echosounders, s7k, datagrams, Navigation))
        .def(nb::init<>(), DOC_C(Navigation, Navigation))
        .def("get_vertical_reference", &Navigation::get_vertical_reference, DOC_C(Navigation, get_vertical_reference))
        .def("set_vertical_reference", &Navigation::set_vertical_reference, DOC_C(Navigation, set_vertical_reference), nb::arg("val"))
        .def("get_latitude", &Navigation::get_latitude, DOC_C(Navigation, get_latitude))
        .def("set_latitude", &Navigation::set_latitude, DOC_C(Navigation, set_latitude), nb::arg("val"))
        .def("get_longitude", &Navigation::get_longitude, DOC_C(Navigation, get_longitude))
        .def("set_longitude", &Navigation::set_longitude, DOC_C(Navigation, set_longitude), nb::arg("val"))
        .def("get_position_accuracy", &Navigation::get_position_accuracy, DOC_C(Navigation, get_position_accuracy))
        .def("set_position_accuracy", &Navigation::set_position_accuracy, DOC_C(Navigation, set_position_accuracy), nb::arg("val"))
        .def("get_height", &Navigation::get_height, DOC_C(Navigation, get_height))
        .def("set_height", &Navigation::set_height, DOC_C(Navigation, set_height), nb::arg("val"))
        .def("get_height_accuracy", &Navigation::get_height_accuracy, DOC_C(Navigation, get_height_accuracy))
        .def("set_height_accuracy", &Navigation::set_height_accuracy, DOC_C(Navigation, set_height_accuracy), nb::arg("val"))
        .def("get_speed", &Navigation::get_speed, DOC_C(Navigation, get_speed))
        .def("set_speed", &Navigation::set_speed, DOC_C(Navigation, set_speed), nb::arg("val"))
        .def("get_course", &Navigation::get_course, DOC_C(Navigation, get_course))
        .def("set_course", &Navigation::set_course, DOC_C(Navigation, set_course), nb::arg("val"))
        .def("get_heading", &Navigation::get_heading, DOC_C(Navigation, get_heading))
        .def("set_heading", &Navigation::set_heading, DOC_C(Navigation, set_heading), nb::arg("val"))
        .def("__eq__", &Navigation::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(Navigation)
        __PYCLASS_DEFAULT_BINARY__(Navigation)
        __PYCLASS_DEFAULT_PRINTING__(Navigation);
}

void init_c_sonarsettings(nb::module_& m)
{
    nb::class_<SonarSettings, S7KDatagram>(m, "SonarSettings", DOC(themachinethatgoesping, echosounders, s7k, datagrams, SonarSettings))
        .def(nb::init<>(), DOC_C(SonarSettings, SonarSettings))
        .def("get_serial_number", &SonarSettings::get_serial_number, DOC_C(SonarSettings, get_serial_number))
        .def("set_serial_number", &SonarSettings::set_serial_number, DOC_C(SonarSettings, set_serial_number), nb::arg("val"))
        .def("get_ping_number", &SonarSettings::get_ping_number, DOC_C(SonarSettings, get_ping_number))
        .def("set_ping_number", &SonarSettings::set_ping_number, DOC_C(SonarSettings, set_ping_number), nb::arg("val"))
        .def("get_multi_ping", &SonarSettings::get_multi_ping, DOC_C(SonarSettings, get_multi_ping))
        .def("set_multi_ping", &SonarSettings::set_multi_ping, DOC_C(SonarSettings, set_multi_ping), nb::arg("val"))
        .def("get_frequency", &SonarSettings::get_frequency, DOC_C(SonarSettings, get_frequency))
        .def("set_frequency", &SonarSettings::set_frequency, DOC_C(SonarSettings, set_frequency), nb::arg("val"))
        .def("get_sample_rate", &SonarSettings::get_sample_rate, DOC_C(SonarSettings, get_sample_rate))
        .def("set_sample_rate", &SonarSettings::set_sample_rate, DOC_C(SonarSettings, set_sample_rate), nb::arg("val"))
        .def("get_receiver_bandwidth", &SonarSettings::get_receiver_bandwidth, DOC_C(SonarSettings, get_receiver_bandwidth))
        .def("set_receiver_bandwidth", &SonarSettings::set_receiver_bandwidth, DOC_C(SonarSettings, set_receiver_bandwidth), nb::arg("val"))
        .def("get_tx_pulse_width", &SonarSettings::get_tx_pulse_width, DOC_C(SonarSettings, get_tx_pulse_width))
        .def("set_tx_pulse_width", &SonarSettings::set_tx_pulse_width, DOC_C(SonarSettings, set_tx_pulse_width), nb::arg("val"))
        .def("get_tx_pulse_type", &SonarSettings::get_tx_pulse_type, DOC_C(SonarSettings, get_tx_pulse_type))
        .def("set_tx_pulse_type", &SonarSettings::set_tx_pulse_type, DOC_C(SonarSettings, set_tx_pulse_type), nb::arg("val"))
        .def("get_tx_pulse_envelope", &SonarSettings::get_tx_pulse_envelope, DOC_C(SonarSettings, get_tx_pulse_envelope))
        .def("set_tx_pulse_envelope", &SonarSettings::set_tx_pulse_envelope, DOC_C(SonarSettings, set_tx_pulse_envelope), nb::arg("val"))
        .def("get_tx_pulse_envelope_parameter", &SonarSettings::get_tx_pulse_envelope_parameter, DOC_C(SonarSettings, get_tx_pulse_envelope_parameter))
        .def("set_tx_pulse_envelope_parameter", &SonarSettings::set_tx_pulse_envelope_parameter, DOC_C(SonarSettings, set_tx_pulse_envelope_parameter), nb::arg("val"))
        .def("get_tx_pulse_mode", &SonarSettings::get_tx_pulse_mode, DOC_C(SonarSettings, get_tx_pulse_mode))
        .def("set_tx_pulse_mode", &SonarSettings::set_tx_pulse_mode, DOC_C(SonarSettings, set_tx_pulse_mode), nb::arg("val"))
        .def("get_max_ping_rate", &SonarSettings::get_max_ping_rate, DOC_C(SonarSettings, get_max_ping_rate))
        .def("set_max_ping_rate", &SonarSettings::set_max_ping_rate, DOC_C(SonarSettings, set_max_ping_rate), nb::arg("val"))
        .def("get_ping_period", &SonarSettings::get_ping_period, DOC_C(SonarSettings, get_ping_period))
        .def("set_ping_period", &SonarSettings::set_ping_period, DOC_C(SonarSettings, set_ping_period), nb::arg("val"))
        .def("get_range_selection", &SonarSettings::get_range_selection, DOC_C(SonarSettings, get_range_selection))
        .def("set_range_selection", &SonarSettings::set_range_selection, DOC_C(SonarSettings, set_range_selection), nb::arg("val"))
        .def("get_power_selection", &SonarSettings::get_power_selection, DOC_C(SonarSettings, get_power_selection))
        .def("set_power_selection", &SonarSettings::set_power_selection, DOC_C(SonarSettings, set_power_selection), nb::arg("val"))
        .def("get_gain_selection", &SonarSettings::get_gain_selection, DOC_C(SonarSettings, get_gain_selection))
        .def("set_gain_selection", &SonarSettings::set_gain_selection, DOC_C(SonarSettings, set_gain_selection), nb::arg("val"))
        .def("get_control_flags", &SonarSettings::get_control_flags, DOC_C(SonarSettings, get_control_flags))
        .def("set_control_flags", &SonarSettings::set_control_flags, DOC_C(SonarSettings, set_control_flags), nb::arg("val"))
        .def("get_projector_id", &SonarSettings::get_projector_id, DOC_C(SonarSettings, get_projector_id))
        .def("set_projector_id", &SonarSettings::set_projector_id, DOC_C(SonarSettings, set_projector_id), nb::arg("val"))
        .def("get_steering_vertical", &SonarSettings::get_steering_vertical, DOC_C(SonarSettings, get_steering_vertical))
        .def("set_steering_vertical", &SonarSettings::set_steering_vertical, DOC_C(SonarSettings, set_steering_vertical), nb::arg("val"))
        .def("get_steering_horizontal", &SonarSettings::get_steering_horizontal, DOC_C(SonarSettings, get_steering_horizontal))
        .def("set_steering_horizontal", &SonarSettings::set_steering_horizontal, DOC_C(SonarSettings, set_steering_horizontal), nb::arg("val"))
        .def("get_beamwidth_vertical", &SonarSettings::get_beamwidth_vertical, DOC_C(SonarSettings, get_beamwidth_vertical))
        .def("set_beamwidth_vertical", &SonarSettings::set_beamwidth_vertical, DOC_C(SonarSettings, set_beamwidth_vertical), nb::arg("val"))
        .def("get_beamwidth_horizontal", &SonarSettings::get_beamwidth_horizontal, DOC_C(SonarSettings, get_beamwidth_horizontal))
        .def("set_beamwidth_horizontal", &SonarSettings::set_beamwidth_horizontal, DOC_C(SonarSettings, set_beamwidth_horizontal), nb::arg("val"))
        .def("get_focal_point", &SonarSettings::get_focal_point, DOC_C(SonarSettings, get_focal_point))
        .def("set_focal_point", &SonarSettings::set_focal_point, DOC_C(SonarSettings, set_focal_point), nb::arg("val"))
        .def("get_projector_weighting", &SonarSettings::get_projector_weighting, DOC_C(SonarSettings, get_projector_weighting))
        .def("set_projector_weighting", &SonarSettings::set_projector_weighting, DOC_C(SonarSettings, set_projector_weighting), nb::arg("val"))
        .def("get_projector_weighting_parameter", &SonarSettings::get_projector_weighting_parameter, DOC_C(SonarSettings, get_projector_weighting_parameter))
        .def("set_projector_weighting_parameter", &SonarSettings::set_projector_weighting_parameter, DOC_C(SonarSettings, set_projector_weighting_parameter), nb::arg("val"))
        .def("get_transmit_flags", &SonarSettings::get_transmit_flags, DOC_C(SonarSettings, get_transmit_flags))
        .def("set_transmit_flags", &SonarSettings::set_transmit_flags, DOC_C(SonarSettings, set_transmit_flags), nb::arg("val"))
        .def("get_hydrophone_id", &SonarSettings::get_hydrophone_id, DOC_C(SonarSettings, get_hydrophone_id))
        .def("set_hydrophone_id", &SonarSettings::set_hydrophone_id, DOC_C(SonarSettings, set_hydrophone_id), nb::arg("val"))
        .def("get_rx_weighting", &SonarSettings::get_rx_weighting, DOC_C(SonarSettings, get_rx_weighting))
        .def("set_rx_weighting", &SonarSettings::set_rx_weighting, DOC_C(SonarSettings, set_rx_weighting), nb::arg("val"))
        .def("get_rx_weighting_parameter", &SonarSettings::get_rx_weighting_parameter, DOC_C(SonarSettings, get_rx_weighting_parameter))
        .def("set_rx_weighting_parameter", &SonarSettings::set_rx_weighting_parameter, DOC_C(SonarSettings, set_rx_weighting_parameter), nb::arg("val"))
        .def("get_rx_flags", &SonarSettings::get_rx_flags, DOC_C(SonarSettings, get_rx_flags))
        .def("set_rx_flags", &SonarSettings::set_rx_flags, DOC_C(SonarSettings, set_rx_flags), nb::arg("val"))
        .def("get_rx_width", &SonarSettings::get_rx_width, DOC_C(SonarSettings, get_rx_width))
        .def("set_rx_width", &SonarSettings::set_rx_width, DOC_C(SonarSettings, set_rx_width), nb::arg("val"))
        .def("get_range_minimum", &SonarSettings::get_range_minimum, DOC_C(SonarSettings, get_range_minimum))
        .def("set_range_minimum", &SonarSettings::set_range_minimum, DOC_C(SonarSettings, set_range_minimum), nb::arg("val"))
        .def("get_range_maximum", &SonarSettings::get_range_maximum, DOC_C(SonarSettings, get_range_maximum))
        .def("set_range_maximum", &SonarSettings::set_range_maximum, DOC_C(SonarSettings, set_range_maximum), nb::arg("val"))
        .def("get_depth_minimum", &SonarSettings::get_depth_minimum, DOC_C(SonarSettings, get_depth_minimum))
        .def("set_depth_minimum", &SonarSettings::set_depth_minimum, DOC_C(SonarSettings, set_depth_minimum), nb::arg("val"))
        .def("get_depth_maximum", &SonarSettings::get_depth_maximum, DOC_C(SonarSettings, get_depth_maximum))
        .def("set_depth_maximum", &SonarSettings::set_depth_maximum, DOC_C(SonarSettings, set_depth_maximum), nb::arg("val"))
        .def("get_absorption", &SonarSettings::get_absorption, DOC_C(SonarSettings, get_absorption))
        .def("set_absorption", &SonarSettings::set_absorption, DOC_C(SonarSettings, set_absorption), nb::arg("val"))
        .def("get_sound_velocity", &SonarSettings::get_sound_velocity, DOC_C(SonarSettings, get_sound_velocity))
        .def("set_sound_velocity", &SonarSettings::set_sound_velocity, DOC_C(SonarSettings, set_sound_velocity), nb::arg("val"))
        .def("get_spreading", &SonarSettings::get_spreading, DOC_C(SonarSettings, get_spreading))
        .def("set_spreading", &SonarSettings::set_spreading, DOC_C(SonarSettings, set_spreading), nb::arg("val"))
        .def("__eq__", &SonarSettings::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(SonarSettings)
        __PYCLASS_DEFAULT_BINARY__(SonarSettings)
        __PYCLASS_DEFAULT_PRINTING__(SonarSettings);
}

void init_c_matchfilter(nb::module_& m)
{
    nb::class_<MatchFilter, S7KDatagram>(m, "MatchFilter", DOC(themachinethatgoesping, echosounders, s7k, datagrams, MatchFilter))
        .def(nb::init<>(), DOC_C(MatchFilter, MatchFilter))
        .def("get_serial_number", &MatchFilter::get_serial_number, DOC_C(MatchFilter, get_serial_number))
        .def("set_serial_number", &MatchFilter::set_serial_number, DOC_C(MatchFilter, set_serial_number), nb::arg("val"))
        .def("get_ping_number", &MatchFilter::get_ping_number, DOC_C(MatchFilter, get_ping_number))
        .def("set_ping_number", &MatchFilter::set_ping_number, DOC_C(MatchFilter, set_ping_number), nb::arg("val"))
        .def("get_operation", &MatchFilter::get_operation, DOC_C(MatchFilter, get_operation))
        .def("set_operation", &MatchFilter::set_operation, DOC_C(MatchFilter, set_operation), nb::arg("val"))
        .def("get_start_frequency", &MatchFilter::get_start_frequency, DOC_C(MatchFilter, get_start_frequency))
        .def("set_start_frequency", &MatchFilter::set_start_frequency, DOC_C(MatchFilter, set_start_frequency), nb::arg("val"))
        .def("get_end_frequency", &MatchFilter::get_end_frequency, DOC_C(MatchFilter, get_end_frequency))
        .def("set_end_frequency", &MatchFilter::set_end_frequency, DOC_C(MatchFilter, set_end_frequency), nb::arg("val"))
        .def("get_window_type", &MatchFilter::get_window_type, DOC_C(MatchFilter, get_window_type))
        .def("set_window_type", &MatchFilter::set_window_type, DOC_C(MatchFilter, set_window_type), nb::arg("val"))
        .def("get_shading", &MatchFilter::get_shading, DOC_C(MatchFilter, get_shading))
        .def("set_shading", &MatchFilter::set_shading, DOC_C(MatchFilter, set_shading), nb::arg("val"))
        .def("get_effective_pulse_width", &MatchFilter::get_effective_pulse_width, DOC_C(MatchFilter, get_effective_pulse_width))
        .def("set_effective_pulse_width", &MatchFilter::set_effective_pulse_width, DOC_C(MatchFilter, set_effective_pulse_width), nb::arg("val"))
        .def("__eq__", &MatchFilter::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(MatchFilter)
        __PYCLASS_DEFAULT_BINARY__(MatchFilter)
        __PYCLASS_DEFAULT_PRINTING__(MatchFilter);
}

void init_c_soundvelocity(nb::module_& m)
{
    nb::class_<SoundVelocity, S7KDatagram>(m, "SoundVelocity", DOC(themachinethatgoesping, echosounders, s7k, datagrams, SoundVelocity))
        .def(nb::init<>(), DOC_C(SoundVelocity, SoundVelocity))
        .def("get_sound_velocity", &SoundVelocity::get_sound_velocity, DOC_C(SoundVelocity, get_sound_velocity))
        .def("set_sound_velocity", &SoundVelocity::set_sound_velocity, DOC_C(SoundVelocity, set_sound_velocity), nb::arg("val"))
        .def("__eq__", &SoundVelocity::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(SoundVelocity)
        __PYCLASS_DEFAULT_BINARY__(SoundVelocity)
        __PYCLASS_DEFAULT_PRINTING__(SoundVelocity);
}

void init_c_absorptionloss(nb::module_& m)
{
    nb::class_<AbsorptionLoss, S7KDatagram>(m, "AbsorptionLoss", DOC(themachinethatgoesping, echosounders, s7k, datagrams, AbsorptionLoss))
        .def(nb::init<>(), DOC_C(AbsorptionLoss, AbsorptionLoss))
        .def("get_absorption_loss", &AbsorptionLoss::get_absorption_loss, DOC_C(AbsorptionLoss, get_absorption_loss))
        .def("set_absorption_loss", &AbsorptionLoss::set_absorption_loss, DOC_C(AbsorptionLoss, set_absorption_loss), nb::arg("val"))
        .def("__eq__", &AbsorptionLoss::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(AbsorptionLoss)
        __PYCLASS_DEFAULT_BINARY__(AbsorptionLoss)
        __PYCLASS_DEFAULT_PRINTING__(AbsorptionLoss);
}

void init_c_spreadingloss(nb::module_& m)
{
    nb::class_<SpreadingLoss, S7KDatagram>(m, "SpreadingLoss", DOC(themachinethatgoesping, echosounders, s7k, datagrams, SpreadingLoss))
        .def(nb::init<>(), DOC_C(SpreadingLoss, SpreadingLoss))
        .def("get_spreading_loss", &SpreadingLoss::get_spreading_loss, DOC_C(SpreadingLoss, get_spreading_loss))
        .def("set_spreading_loss", &SpreadingLoss::set_spreading_loss, DOC_C(SpreadingLoss, set_spreading_loss), nb::arg("val"))
        .def("__eq__", &SpreadingLoss::operator==, nb::arg("other"))
        __PYCLASS_DEFAULT_COPY__(SpreadingLoss)
        __PYCLASS_DEFAULT_BINARY__(SpreadingLoss)
        __PYCLASS_DEFAULT_PRINTING__(SpreadingLoss);
}


void init_c_s7krecords(nb::module_& m)
{
    init_c_referencepoint(m);
    init_c_position(m);
    init_c_rollpitchheave(m);
    init_c_heading(m);
    init_c_navigation(m);
    init_c_sonarsettings(m);
    init_c_matchfilter(m);
    init_c_soundvelocity(m);
    init_c_absorptionloss(m);
    init_c_spreadingloss(m);
}

}
}
}
}
