#include <algorithm>
#include <bitset>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/find.hpp>
#include <boost/flyweight.hpp>
#include <boost/iostreams/device/mapped_file.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/sort/sort.hpp>
#include <complex>
#include <filesystem>
#include <fmt/core.h>
#include <fstream>
#include <iostream>
#include <limits>
#include <magic_enum.hpp>
#include <map>
#include <memory>
#include <pugixml.hpp>
#include <pybind11/pybind11.h>
#include <ranges>
#include <set>
#include <sstream>
#include <string>
#include <themachinethatgoesping/algorithms/geoprocessing/datastructures/xyz.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/attitudedatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/clockdatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/depthorheightdatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/em3000datagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/em3000unknown.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/extradetections.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/extraparameters.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/headingdatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/installationparameters.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/networkattitudevelocitydatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/positiondatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/puidoutput.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/pustatusoutput.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/qualityfactordatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/rawrangeandangle.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/runtimeparameters.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/seabedimagedata.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/singlebeamechosounderdepth.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/soundspeedprofiledatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/attitudedatagramattitude.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/extradetectionsdetectionclasses.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/extradetectionsextradetections.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/flag_detection_information.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/networkattitudevelocitydatagramattitude.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/rawrangeandanglebeam.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/rawrangeandangletransmitsector.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/sampleamplitudesstructure.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/seabedimagedatabeam.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/watercolumndatagrambeam.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/watercolumndatagramtransmitsector.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/substructures/xyzdatagrambeam.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/surfacesoundspeeddatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/watercolumndatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/datagrams/xyzdatagram.hpp>
#include <themachinethatgoesping/echosounders/em3000/em3000_datagrams.hpp>
#include <themachinethatgoesping/echosounders/em3000/em3000_types.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatacontainers/em3000datagramcontainer.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatacontainers/em3000pingcontainer.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000annotationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000annotationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000configurationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000configurationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000datagraminterface.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000environmentdatainterface.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000environmentdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000navigationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000navigationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000otherfiledatainterface.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000otherfiledatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000pingdatainterface.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatainterfaces/em3000pingdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatatypes/_sub/watercolumninformation.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatatypes/em3000ping.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatatypes/em3000pingbottom.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatatypes/em3000pingcommon.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatatypes/em3000pingrawdata.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatatypes/em3000pingwatercolumn.hpp>
#include <themachinethatgoesping/echosounders/em3000/filedatatypes/private_structures/watercolumninformation.hpp>
#include <themachinethatgoesping/echosounders/em3000/fileem3000.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datacontainers/datagramcontainer.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datacontainers/pingcontainer.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_annotationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_annotationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_configurationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_configurationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_datagraminterface.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_environmentdatainterface.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_environmentdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_filedatainterface.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_filedatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_navigationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_navigationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_pingdatainterface.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datainterfaces/i_pingdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datastreams/mappedfilestream.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datatypes/datagraminfo.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datatypes/i_ping.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datatypes/i_pingbottom.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datatypes/i_pingcommon.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/datatypes/i_pingwatercolumn.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/helper/deduplicatebuffer.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/i_inputfile.hpp>
#include <themachinethatgoesping/echosounders/filetemplates/internal/inputfilemanager.hpp>
#include <themachinethatgoesping/echosounders/pingtools/beamsampleselection.hpp>
#include <themachinethatgoesping/echosounders/pingtools/beamselection.hpp>
#include <themachinethatgoesping/echosounders/pingtools/pingsampleselector.hpp>
#include <themachinethatgoesping/echosounders/pingtools/readsamplerange.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/FIL1.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/MRU0.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/NME0.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/RAW3.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/TAG0.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/XML0.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/i_raw3data.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/raw3dataangle.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/raw3datacomplexfloat32.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/raw3datapower.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/raw3datapowerandangle.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/raw3dataskipped.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/raw3datatypes.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/raw3datatypes/t_raw3datatype.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/simraddatagram.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/simradunknown.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/channelconfiguration.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/helper.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration_sensor.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration_sensor_telegram.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration_sensor_telegramvalue.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration_transceiver.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration_transceiver_channel.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration_transceiver_channel_frequencypar.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_configuration_transducer.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_environment.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_environment_transducer.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_initialparameter.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_node.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_parameter.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_parameter_channel.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_pingsequence.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_pingsequence_ping.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xml_sensor.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xmlconfigurationactivepingmode.hpp>
#include <themachinethatgoesping/echosounders/simrad/datagrams/xml_datagrams/xmlconfigurationtransceiverchanneltransducer.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatacontainers/simradfiledatacontainers.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradannotationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradannotationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradconfigurationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradconfigurationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simraddatagraminterface.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradenvironmentdatainterface.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradenvironmentdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradnavigationdatainterface.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradnavigationdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradotherfiledatainterface.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradotherfiledatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradpingdatainterface.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatainterfaces/simradpingdatainterfaceperfile.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatatypes/simradping.hpp>
#include <themachinethatgoesping/echosounders/simrad/filedatatypes/simradpingrawdata.hpp>
#include <themachinethatgoesping/echosounders/simrad/filesimradraw.hpp>
#include <themachinethatgoesping/echosounders/simrad/simrad_datagrams.hpp>
#include <themachinethatgoesping/echosounders/simrad/simrad_types.hpp>
#include <themachinethatgoesping/navigation/datastructures/positionaloffsets.hpp>
#include <themachinethatgoesping/navigation/navigationinterpolatorlatlon.hpp>
#include <themachinethatgoesping/navigation/nmea_0183.hpp>
#include <themachinethatgoesping/navigation/sensorconfiguration.hpp>
#include <themachinethatgoesping/tools/classhelper/objectprinter.hpp>
#include <themachinethatgoesping/tools/classhelper/stream.hpp>
#include <themachinethatgoesping/tools/hashhelper.hpp>
#include <themachinethatgoesping/tools/helper.hpp>
#include <themachinethatgoesping/tools/helper/defaultsharedpointermap.hpp>
#include <themachinethatgoesping/tools/progressbars.hpp>
#include <themachinethatgoesping/tools/pyhelper/pyindexer.hpp>
#include <themachinethatgoesping/tools/timeconv.hpp>
#include <unordered_map>
#include <variant>
#include <vector>
#include <xtensor/xadapt.hpp>
#include <xtensor/xarray.hpp>
#include <xtensor/xio.hpp>
#include <xtensor/xmath.hpp>
#include <xtensor/xnoalias.hpp>
#include <xtensor/xview.hpp>

